version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    open-pull-requests-limit: 2
    versioning-strategy: increase
    schedule:
      interval: monthly
    labels:
      - 'pr: dependencies'
